applications/rbac/models.py
import datetime

from applications import db


class Menu(db.Model):
    """
    菜单表
    """
    __tablename__ = 'menu'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(10))

    # 双向关联，用于跨表查询
    perm_groups = db.relationship('PermissionGroup', backref='menu')

    def __str__(self):
        return '<Menu %s>' % self.title


class PermissionGroup(db.Model):
    """
    权限组表
    """
    __tablename__ = 'permissiongroup'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(10))
    menu_id = db.Column(db.Integer, db.ForeignKey('menu.id'))

    # 双向关联，用于跨表查询
    permissions = db.relationship('Permission', backref='perm_group')

    def __str__(self):
        return '<PermissionGroup %s>' % self.title


# 权限—角色关联表
permission_role = db.Table('permission_role', db.metadata,
                           db.Column('permission_id', db.Integer,
                                     db.ForeignKey('permission.id', ondelete='CASCADE', onupdate='CASCADE')),
                           db.Column('role_id', db.Integer,
                                     db.ForeignKey('role.id', ondelete='CASCADE', onupdate='CASCADE'))
                           )


class Permission(db.Model):
    """
    权限表
    """
    __tablename__ = 'permission'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(10))
    url = db.Column(db.String(64))
    menu_ref = db.Column(db.Integer, db.ForeignKey('permission.id'))  # 自关联
    code = db.Column(db.String(10))
    group_id = db.Column(db.Integer, db.ForeignKey('permissiongroup.id'))

    # 自关联声明
    self_ref = db.relationship('Permission', remote_side=[id])

    # 多对多的双向关联，用于跨表查询
    roles = db.relationship('Role', secondary=permission_role, passive_deletes=True)

    def __str__(self):
        return '<Permission> %s' % self.title


# 用户—角色关联表
user_role = db.Table('user_role', db.metadata,
                     db.Column('user_id', db.Integer, db.ForeignKey('user.id', ondelete='CASCADE', onupdate='CASCADE')),
                     db.Column('role_id', db.Integer, db.ForeignKey('role.id', ondelete='CASCADE', onupdate='CASCADE'))
                     )


class Role(db.Model):
    """
    角色表
    """
    __tablename__ = 'role'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(10))

    # 多对多的双向关联，用于跨表查询
    permissions = db.relationship('Permission', secondary=permission_role, passive_deletes=True)
    users = db.relationship('User', secondary=user_role, passive_deletes=True)

    def __str__(self):
        return '<Role %s>' % self.name


class User(db.Model):
    """
    用户信息表
    """
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(16))
    password = db.Column(db.String(100))
    create_time = db.Column(db.DateTime, default=datetime.datetime.now)

    # 多对多的双向关联，用于跨表查询
    roles = db.relationship('Role', secondary=user_role, passive_deletes=True)

    def check_password(self, password):
        from werkzeug.security import check_password_hash
        return check_password_hash(self.password, password)

    def __str__(self):
        return '<User %s>' % self.username

# 笔记：
# 一对一关联的时候，在relationship里设置uselist为False
# 在Association-object模式中，级联删除要设置viewonly为False，待研究
# 级联删除的实现方式之一：在Foreign中添加ondelete='CASCADE', onupdate='CASCADE'，在relationship中添加passive_deletes=True

applications/rbac/forms.py
from flask_wtf import FlaskForm
from wtforms.ext.sqlalchemy.orm import model_form
from wtforms import validators
from wtforms import widgets

from applications import db
from . import models

LoginForm = model_form(models.User, base_class=FlaskForm, db_session=db.session, only=['username', 'password'],
                       field_args={
                           "username": {
                               "label": '用户名',
                               "validators": [
                                   validators.DataRequired(message='用户名不能为空'),
                                   validators.Length(min=4, max=16, message='密码长度必须大于%(min)d且小于%(max)d')
                               ],
                               "render_kw": {'class': 'form-control'}
                           },
                           "password": {
                               "label": '密码',
                               "widget": widgets.PasswordInput(),
                               "validators": [
                                   validators.DataRequired(message='密码不能为空'),
                                   validators.Length(min=6, max=16, message='密码长度必须大于%(min)d且小于%(max)d')
                               ],
                               "render_kw": {'class': 'form-control'}

                           }
                       })

UserForm = model_form(models.User, base_class=FlaskForm, db_session=db.session, exclude=['create_time'],
                      field_args={
                          "username": {
                              "label": '用户名',
                              "validators": [
                                  validators.DataRequired(message='用户名不能为空'),
                                  validators.Length(min=4, max=16, message='密码长度必须大于%(min)d且小于%(max)d')
                              ],
                              "render_kw": {'class': 'form-control'}
                          },
                          "password": {
                              "label": '密码',
                              "widget": widgets.PasswordInput(),
                              "validators": [
                                  validators.DataRequired(message='密码不能为空'),
                                  validators.Length(min=6, max=16, message='密码长度必须大于%(min)d且小于%(max)d')
                              ],
                              "render_kw": {'class': 'form-control'}

                          },
                          "roles": {
                              "label": '角色',
                              "widget": widgets.Select(),
                              "validators": [
                                  validators.DataRequired(message='角色不能为空'),
                              ],
                              "render_kw": {'class': 'form-control'}
                          }
                      })

applications/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)  # type:Flask
    app.debug = True

    # app.config.from_object('settings.TestConfig')
    # app.config.from_object('settings.DevConfig')
    app.config.from_object('settings.ProConfig')
    db.init_app(app)  # 在app.config中添加db相关的配置

    from . import rbac
    from .rbac.auth import Auth
    app.register_blueprint(rbac.rbac)
    Auth(app)  # 使用自定义插件添加一些功能

    return app

applications/rbac/__init__.py
from flask import Blueprint

rbac = Blueprint('rbac', __name__)

from . import templatetags
from . import views

applications/rbac/auth.py
"""
自定义插件，主要功能有：
    1、添加中间件
    2、为模板添加可直接使用的变量
    3、为app提供链接到该功能内部的接口，使用current_app.auth_manager调用
"""
import re

from flask import request, session, redirect, url_for


class Auth(object):
    def __init__(self, app=None):
        self.app = app
        if app:
            self.init_app(app)

    def init_app(self, app):
        app.auth_manager = self
        app.before_request(self.check_login)
        app.before_request(self.check_permission)
        app.context_processor(self.auth_context_processor)

    def auth_context_processor(self):
        """
        为模板添加可直接引用的变量
        :return: 返回一个字典，固定格式
        """
        return dict(current_user=session.get(self.app.config['USER_INFO']))

    def check_valid_urls(self):
        """
        验证当前url是否在白名单中
        :return:匹配到白名单中的url，返回True
        """
        current_url = request.path
        for url in self.app.config['VALID_URLS']:
            re_url = '^{}$'.format(url)
            if re.match(re_url, current_url):
                return True

    def check_login(self):
        """
        检测是否有用户登录，如果没有，跳转到登录页面
        """
        if self.check_valid_urls():
            return None
        if not session.get(self.app.config['USER_INFO']):
            return redirect(url_for('rbac.login'))

    def check_permission(self):
        """
        验证当前用户是否拥有访问当前url的权限
        :return:
        """
        if self.check_valid_urls():
            return None

        flag = False
        current_url = request.path

        for urls_dict in session.get(self.app.config['PERM_INFO_DICT']).values():
            for url_info in urls_dict.get('urls_info'):
                re_url = '^{}$'.format(url_info.get('url'))
                if re.match(re_url, current_url):
                    session[self.app.config['PERM_CODES_LIST']] = urls_dict.get('codes')
                    flag = True
                    break
            if flag:
                break

        if not flag:
            return '无权访问'

applications/rbac/views.py
"""
测试rbac
"""
from flask import request, session, current_app
from flask import redirect, url_for, render_template

from applications import db
from . import rbac  # 蓝图
from . import models, forms
from .service import init_permission


class Codes(object):
    """
    封装session中权限的codes信息，便于在模板中调用
    """

    def __init__(self, codes_list):
        self.codes_list = codes_list

    def has_add(self):
        if 'add' in self.codes_list:
            return True

    def has_edit(self):
        if 'edit' in self.codes_list:
            return True

    def has_del(self):
        if 'del' in self.codes_list:
            return True


@rbac.route('/')
def index():
    """
    主页
    """
    userinfo = session.get(current_app.config["USER_INFO"])
    if userinfo:
        urls_info = session.get(current_app.config["PERM_SIDE_LIST"])
        return render_template('index.html', urls_info=urls_info)
    else:
        return render_template('index.html')


@rbac.route('/login', methods=['GET', 'POST'])
def login():
    """
    登录
    """
    if request.method == 'GET':
        login_form = forms.UserForm()
        return render_template('login.html', login_form=login_form)
    else:
        login_form = forms.LoginForm(request.form)
        if not login_form.validate_on_submit():
            return render_template('login.html', login_form=login_form)
        else:
            username = login_form.data.get('username')
            password = login_form.data.get('password')

            user_obj = db.session.query(models.User).filter_by(username=username).first()

            if user_obj:
                if user_obj.check_password(password):
                    init_permission(user_obj)
                    return redirect(url_for('rbac.index'))
                else:
                    login_form.password.errors.append('密码错误')
                    return render_template('login.html', login_form=login_form)
            else:
                login_form.username.errors.append('用户不存在')
                return render_template('login.html', login_form=login_form)


@rbac.route('/logout')
def logout():
    """
    注销
    """
    session.clear()
    return redirect(url_for('rbac.login'))


@rbac.route('/test')
def test():
    # 创建用户
    # from werkzeug.security import generate_password_hash
    # new_user = models.User(username='test', password=generate_password_hash('abc123'))
    # db.session.add(new_user)
    # db.session.commit()

    # 修改密码
    # objs = db.session.query(models.User).all()
    # for obj in objs:
    #     obj.password = generate_password_hash('abc123')
    # db.session.commit()

    return '测试'


###### 用户相关 ######
@rbac.route('/userinfo')
def userinfo():
    codes = Codes(session.get(current_app.config["PERM_CODES_LIST"]))
    user_list = db.session.query(models.User).all()
    res = render_template('userinfo.html', codes=codes, user_list=user_list)
    return res


@rbac.route('/userinfo/add', methods=['GET', 'POST'])
def user_add():
    if request.method == 'GET':
        user_form = forms.LoginForm()
        return render_template('user_add.html', user_form=user_form)
    else:
        user_form = forms.LoginForm(request.form)
        if not user_form.validate_on_submit():
            return render_template('user_add.html', user_form=user_form)
        else:
            username = user_form.data.get('username')
            password = user_form.data.get('password')
            new_user = models.User(username=username, password=password)
            db.session.add(new_user)
            db.session.commit()

            return '添加用户或注册'


@rbac.route('/userinfo/edit/<int:id>', methods=['GET', 'POST'])
def user_edit(id):
    if request.method == 'GET':
        # 此处仅为测试，具体业务逻辑请自行实现
        return '编辑用户'
    else:
        # 此处仅为测试，具体业务逻辑请自行实现
        return 'POST提交编辑用户'


@rbac.route('/userinfo/del/<int:id>')
def user_del(id):
    db.session.query(models.User).filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for('rbac.userinfo'))

    # return '删除用户'


###### 订单相关 ######
@rbac.route('/order')
def order():
    return render_template('order.html')


@rbac.route('/order/add', methods=['GET', 'POST'])
def order_add():
    return '添加用户或注册'


@rbac.route('/order/edit/<int:id>', methods=['GET', 'POST'])
def order_edit(id):
    if request.method == 'GET':
        # 此处仅为测试，具体业务逻辑请自行实现
        return '编辑订单'
    else:
        # 此处仅为测试，具体业务逻辑请自行实现
        return 'POST提交编辑订单'


@rbac.route('/order/del/<int:id>')
def order_del(id):
    return '删除订单'

applications/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base_template.css') }}">
    {% block my_css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<!-- 导航条 -->
<nav class="navbar navbar-inverse">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Home</a>
        </div>


        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if session.get('userinfo') %}
                    <li><a href="javascript:void (0)">{{ session.get('userinfo').get('username') }}</a></li>
                    <li><a href="{{ url_for('rbac.logout') }}">注销</a></li>
                {% else %}
                    <li><a href="{{ url_for('rbac.login') }}">登录</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block main %}{% endblock %}

<script src="{{ url_for('static',filename='jquery-3.2.1.min.js') }}"></script>
<script src="{{ url_for('static',filename='bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/base_template.js') }}"></script>
{% block my_js %}{% endblock %}

</body>
</html>

applications/templates/has_menu_base.html
{% extends 'base_template.html' %}

<!-- 页面主体 -->
{% block main %}

    <div class="container-fluid">
        <div class="row">
            <div class="sidebar col-sm-3 col-md-2">
                {% for dict_item in get_side_dict().values() %}
                    <ul class="item">
                        <btn class="title btn btn-info">{{ dict_item.get('menu_title') }}</btn>

                        {#下面的代码有部分重复，但是考虑到文档的排版，不对其做删改#}
                        {% if dict_item.get('menu_active') %}
                            <div class="list">
                                {% for url_dict in dict_item.get('urls_info') %}
                                    {% if  url_dict.get('active') %}
                                        <li><a href="{{ url_dict.get('url') }}"
                                               class="active">{{ url_dict.get('url_title') }}</a>
                                        </li>
                                    {% else %}
                                        <li><a href="{{ url_dict.get('url') }}">{{ url_dict.get('url_title') }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% else %}
                            <div class="list hidden">
                                {% for url_dict in dict_item.get('urls_info') %}
                                    {% if  url_dict.active %}
                                        <li><a href="{{ url_dict.get('url') }}"
                                               class="active">{{ url_dict.get('url_title') }}</a>
                                        </li>
                                    {% else %}
                                        <li><a href="{{ url_dict.get('url') }}">{{ url_dict.get('url_title') }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}

                    </ul>
                {% endfor %}
            </div>

            <div class="body col-sm-9 col-md-10">
                {% block content %}{# 主体内容 #}{% endblock %}
            </div>
        </div>
    </div>

{% endblock main %}

applications/templates/index.html
{% extends 'no_menu_base.html' %}

{% block title %}首页{% endblock %}

{% block content %}
    <h1>主页</h1>

    {% if session.get('userinfo') %}
        <p>显示所有权限</p>
        <ul>
            {% for url_info in urls_info %}
                <li>
                    <a href="{{ url_info.get('url') }}">{{ url_info.get('url_title') }}</a>
                    {{ url_info.get('url') }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock content %}

applications/templates/login.html
{% extends 'no_menu_base.html' %}

{% block title %}登录{% endblock %}

{% block content %}
    <form method="post" class="form-horizontal">
        {{ login_form.csrf_token }}
        <div class="form-group">
            {{ login_form.username.label }}
            <div>
                {{ login_form.username }}
            </div>
            <span class="help-block">{{ login_form.username.errors[0] }}</span>
        </div>

        <div class="form-group">
            {{ login_form.password.label }}
            <div>
                {{ login_form.password }}
            </div>
            <span class="help-block">{{ login_form.password.errors[0] }}</span>
        </div>
        <input type="submit" value="登录" class="btn btn-primary">

    </form>
{% endblock content %}

applications/templates/no_menu_base.html
{% extends 'base_template.html' %}

{% block main %}

    <div class="container">
        {% block content %}{# 主体内容 #}{% endblock %}
    </div>

{% endblock main %}

applications/templates/order.html
{% extends 'has_menu_base.html' %}

{% block title %}订单列表{% endblock %}


{% block content %}
    主体
{% endblock content %}

applications/templates/user_add.html
{% extends 'has_menu_base.html' %}

{% block title %}添加用户{% endblock %}

{% block content %}
    <form method="post" class="form-horizontal">
        {{ user_form.csrf_token }}
        <div class="form-group">
            {{ user_form.username.label }}
            <div>
                {{ user_form.username }}
            </div>
            {{ user_form.username.errors[0] }}
        </div>

        <div class="form-group">
            {{ user_form.password.label }}
            <div>
                {{ user_form.password }}
            </div>
            {{ user_form.password.errors[0] }}
        </div>
        <div>
            {{ user_form.roles }}
        </div>
        <input type="submit" value="提交" class="btn btn-primary">

    </form>
{% endblock %}

applications/templates/userinfo.html
{% extends 'has_menu_base.html' %}

{% block title %}用户列表{% endblock %}

{% block content %}
    {% if codes.has_add() %}
        <a href="{{ url_for('rbac.user_add') }}" class="btn btn-primary">添加用户</a>
    {% endif %}
    <p></p>
    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>用户名</th>
            <th>角色</th>
            <th>操作</th>
        </tr>
        </thead>

        <tbody>
        {% for user in user_list %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>
                    {% for role in user.roles %}
                        <span>{{ role.name }}</span>
                    {% endfor %}
                </td>
                <td>
                    {% if codes.has_edit() %}
                        <span><a href="{{ url_for('rbac.user_edit',id=user.id) }}">编辑</a></span>
                    {% endif %}
                    {% if codes.has_del() %}
                        <span><a href="{{ url_for('rbac.user_del',id=user.id) }}">删除</a></span>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}